[[".gitlab-ci.yml".contains]]
line = "    - mypy -p ims --junit-xml report-mypy.xml"
[[".gitlab-ci.yml".contains]]
line = "    - apache-license-check --copyright \"2019-2020 SURF\" ims"
[[".gitlab-ci.yml".contains]]
line = "    - flake8 --tee --output-file flake8.txt; exit_code=$?; flake8_junit flake8.txt report-flake8.xml"
[[".gitlab-ci.yml".contains]]
line = "    - if [ $exit_code -ne 0 ]; then exit 1; fi;"
[[".gitlab-ci.yml".contains]]
line = "    - isort -c ims"
[[".gitlab-ci.yml".contains]]
line = "    - black --check ."
[[".gitlab-ci.yml".contains]]
line = "    - pytest --cov=ims --cov-branch --junitxml=report-pytest-unit.xml --cov-fail-under="
